#ifdef CS_P0
    case '0': { Write(buf, offset, p0); break; }
#endif

#ifdef CS_P1
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
#endif

#ifdef CS_P2
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
#endif

#ifdef CS_P3
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
#endif

#ifdef CS_P4
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
    case '4': { Write(buf, offset, p4); break; }
#endif

#ifdef CS_P5
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
    case '4': { Write(buf, offset, p4); break; }
    case '5': { Write(buf, offset, p5); break; }
#endif

#ifdef CS_P6
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
    case '4': { Write(buf, offset, p4); break; }
    case '5': { Write(buf, offset, p5); break; }
    case '6': { Write(buf, offset, p6); break; }
#endif

#ifdef CS_P7
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
    case '4': { Write(buf, offset, p4); break; }
    case '5': { Write(buf, offset, p5); break; }
    case '6': { Write(buf, offset, p6); break; }
    case '7': { Write(buf, offset, p7); break; }
#endif

#ifdef CS_P8
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
    case '4': { Write(buf, offset, p4); break; }
    case '5': { Write(buf, offset, p5); break; }
    case '6': { Write(buf, offset, p6); break; }
    case '7': { Write(buf, offset, p7); break; }
    case '8': { Write(buf, offset, p8); break; }
#endif

#ifdef CS_P9
    case '0': { Write(buf, offset, p0); break; }
    case '1': { Write(buf, offset, p1); break; }
    case '2': { Write(buf, offset, p2); break; }
    case '3': { Write(buf, offset, p3); break; }
    case '4': { Write(buf, offset, p4); break; }
    case '5': { Write(buf, offset, p5); break; }
    case '6': { Write(buf, offset, p6); break; }
    case '7': { Write(buf, offset, p7); break; }
    case '8': { Write(buf, offset, p8); break; }
    case '9': { Write(buf, offset, p9); break; }
#endif
