#ifdef CS_P0
    case '0': { (*this) << p0; break; }
#endif

#ifdef CS_P1
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
#endif

#ifdef CS_P2
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
#endif

#ifdef CS_P3
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
#endif

#ifdef CS_P4
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
    case '4': { (*this) << p4; break; }
#endif

#ifdef CS_P5
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
    case '4': { (*this) << p4; break; }
    case '5': { (*this) << p5; break; }
#endif

#ifdef CS_P6
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
    case '4': { (*this) << p4; break; }
    case '5': { (*this) << p5; break; }
    case '6': { (*this) << p6; break; }
#endif

#ifdef CS_P7
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
    case '4': { (*this) << p4; break; }
    case '5': { (*this) << p5; break; }
    case '6': { (*this) << p6; break; }
    case '7': { (*this) << p7; break; }
#endif

#ifdef CS_P8
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
    case '4': { (*this) << p4; break; }
    case '5': { (*this) << p5; break; }
    case '6': { (*this) << p6; break; }
    case '7': { (*this) << p7; break; }
    case '8': { (*this) << p8; break; }
#endif

#ifdef CS_P9
    case '0': { (*this) << p0; break; }
    case '1': { (*this) << p1; break; }
    case '2': { (*this) << p2; break; }
    case '3': { (*this) << p3; break; }
    case '4': { (*this) << p4; break; }
    case '5': { (*this) << p5; break; }
    case '6': { (*this) << p6; break; }
    case '7': { (*this) << p7; break; }
    case '8': { (*this) << p8; break; }
    case '9': { (*this) << p9; break; }
#endif
